package inf112.skeleton.app.board.tiles;

public enum TileType {

    TILE_GROUND (5),
    TILE_HOLE (6),

    TILE_WALL_SOUTH_EAST (8),
    TILE_WALL_NORTH_EAST (16),
    TILE_WALL_NORTH_WEST (24),
    TILE_WALL_SOUTH_WEST(32),

    TILE_WALL_EAST (23),
    TILE_WALL_SOUTH (29),
    TILE_WALL_WEST (30),
    TILE_WALL_NORTH (31),




    TILE_CONVEYOR_FAST_NORTH (13),
    TILE_CONVEYOR_FAST_EAST (14),
    TILE_CONVEYOR_FAST_SOUTH (21),
    TILE_CONVEYOR_FAST_WEST (22),


    TILE_CONVEYOR_FAST_WEST_TO_SOUTH (17),
    TILE_CONVEYOR_FAST_NORTH_TO_EAST (25),
    TILE_CONVEYOR_FAST_WEST_TO_NORTH (27),
    TILE_CONVEYOR_FAST_NORTH_TO_WEST (28),

    TILE_CONVEYOR


    TILE_CONVEYOR_SLOW_NORTH (49),
    TILE_CONVEYOR_SLOW_SOUTH (50),
    TILE_CONVEYOR_SLOW_WEST (51),
    TILE_CONVEYOR_SLOW_EAST (52),
    TILE_GEAR_RED (53),
    TILE_GEAR_GREEN (54),
    TILE_FLAG_1 (55),

    TILE_FLAG_2 (63),
    TILE_FLAG_3 (71),
    TILE_FLAG_$ (79),


    TILE_START_POS_1 (121),
    TILE_START_POS_2 (122),
    TILE_START_POS_3 (123),
    TILE_START_POS_4 (124),
    TILE_START_POS_5 (125),
    TILE_START_POS_6 (126),
    TILE_START_POS_7 (127),
    TILE_START_POS_8 (128),

    TILE_ROTATE_LEFT (53),
    TILE_ROTATE_RIGHT (54);


    private final int tileID;

    TileType(int tileID) {
        this.tileID = tileID;
    }
}
